/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaogeral;

import java.awt.event.KeyEvent;

/**
 *
 * @author Programador Henrique
 */
public class TeladeAutenticacao extends javax.swing.JFrame {

    /**
     * Creates new form TeladeAutenticacao
     */
    public TeladeAutenticacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        lbllogin = new javax.swing.JLabel();
        lblprogram = new javax.swing.JLabel();
        lbldesenvolvedor = new javax.swing.JLabel();
        lblversion = new javax.swing.JLabel();
        jButtonaccess = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        lblfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        lblUser.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblUser.setText("Usuário");
        getContentPane().add(lblUser);
        lblUser.setBounds(150, 50, 40, 14);

        lblPassword.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblPassword.setText("Senha");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(150, 80, 40, 14);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(200, 50, 80, 20);

        jPasswordFieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPassKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldPass);
        jPasswordFieldPass.setBounds(200, 80, 80, 20);

        lbllogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loginmanager_10029.png"))); // NOI18N
        getContentPane().add(lbllogin);
        lbllogin.setBounds(10, 10, 120, 120);

        lblprogram.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblprogram.setForeground(new java.awt.Color(153, 0, 51));
        lblprogram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblprogram.setText("Marcenarias Program");
        getContentPane().add(lblprogram);
        lblprogram.setBounds(10, 140, 140, 20);

        lbldesenvolvedor.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lbldesenvolvedor.setForeground(new java.awt.Color(0, 51, 204));
        lbldesenvolvedor.setText("Desenvolvido por: Henrique Augusto");
        getContentPane().add(lbldesenvolvedor);
        lbldesenvolvedor.setBounds(100, 10, 190, 14);

        lblversion.setText("versão: 1.0");
        getContentPane().add(lblversion);
        lblversion.setBounds(240, 150, 60, 14);

        jButtonaccess.setText("Acessar");
        jButtonaccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaccessActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonaccess);
        jButtonaccess.setBounds(140, 110, 71, 23);

        jButtonexit.setText("Sair");
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexit);
        jButtonexit.setBounds(220, 110, 51, 23);

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        lblfundo.setText("Tela de Login");
        getContentPane().add(lblfundo);
        lblfundo.setBounds(0, 0, 390, 168);

        setSize(new java.awt.Dimension(316, 206));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        // codigo para sair do sistema
        System.exit(0);
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jPasswordFieldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPassKeyPressed
        // codigo para quando o usuário teclar enter o sistema abrir.
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            
            if(jTextFieldUser.getText().equals("Admin")&&jPasswordFieldPass.getText().equals("admin")){
            TelaPrincipal TelaPrincipal = new TelaPrincipal();
        TelaPrincipal.setVisible(true);
        dispose();
    }
        else{
                JOption.showMessageDialog(rootPane, "ACESSO NEGADO!");
            }
    }//GEN-LAST:event_jPasswordFieldPassKeyPressed

    private void jButtonaccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaccessActionPerformed
        // codigo para quando o usuário teclar enter o sistema abrir.
        
            
            if(jTextFieldUser.getText().equals("Admin")&&jPasswordFieldPass.getText().equals("admin")){
            TelaPrincipal TelaPrincipal = new TelaPrincipal();
        TelaPrincipal.setVisible(true);
        dispose();
    }
        else{
                JOption.showMessageDialog(rootPane, "ACESSO NEGADO!");
            }
    }//GEN-LAST:event_jButtonaccessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeladeAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeladeAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeladeAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeladeAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TeladeAutenticacao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonaccess;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lbldesenvolvedor;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblprogram;
    private javax.swing.JLabel lblversion;
    // End of variables declaration//GEN-END:variables
}
